# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: florian <florian@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/11 09:47:22 by fberthou          #+#    #+#              #
#    Updated: 2024/11/20 14:18:47 by florian          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# --- COLORS --- #
RESET_COLOR	= \033[0m
GREEN		= \033[32m
YELLOW		= \033[33m

# --- PROG NAME --- #
NAME		= sed_loser

# --- SET PATHS --- #
#PROJECT#
HDR_PATH	= .
SRC_PATH	= .

#TEMPORARY FILES#
BUILD_PATH	= .build

# --- COMPILATION --- #
CC 			=	c++
COMPFLAGS	=	-Wall -Wextra -Werror -std=c++98

SRC		=	$(SRC_PATH)/main.cpp $(SRC_PATH)/NotSed.cpp $(SRC_PATH)/almostSed.cpp

### ---- TEMPORARY FILES ---- ###
OBJ	= $(SRC:$(SRC_PATH)/%.cpp=$(BUILD_PATH)/%.o)

### --- CALL --- ###
default	: all
all		: $(NAME)

### --- LINKER --- ###
$(NAME)	: $(OBJ)
	$(CC) $^ -o $@
	@echo "$(GREEN)-- sed_loser ready --$(RESET_COLOR)"

#######     OBJECTS    #######
$(BUILD_PATH)/%.o : $(SRC_PATH)/%.cpp Makefile $(HDR_PATH)/*.hpp
	@mkdir -p $(dir $@)
	$(CC) $(COMPFLAGS) -I$(HDR_PATH) -c $< -o $@

### --- CLEAN MANAGEMENT --- ###
clean	:
	@rm -rf $(BUILD_PATH) *.replace
	@echo "$(YELLOW)-- removed temporary files --$(RESET_COLOR)"

fclean	:
	@rm -rf $(BUILD_PATH) $(NAME) *.replace
	@rm -rf $(BUILD_PATH) $(NAME) ./test/test_files/*.replace
	@echo "$(YELLOW)-- removed sed_loser --$(RESET_COLOR)"

re		: fclean all

.PHONY	: clean fclean re default all
